# Generated by Django 4.2.7 on 2025-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_payment_method_qrpaymentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('google_pay', 'Google Pay'), ('apple_pay', 'Apple Pay'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.DeleteModel(
            name='QRPaymentSession',
        ),
    ]
