# Generated by Django 4.2.7 on 2025-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_qr_payment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Tarjeta'), ('paypal', 'PayPal')], default='card', max_length=50),
        ),
    ]
